Add readme.md for iOS project
johngrib/farm-timer pull request #7
Opened 2019-03-15 15:18 UTC by rollmind

Writing readme.md file for iOS project.

It has abstract of struct of projects and information of main functions.

2019-03-15 23:39 UTC, johngrib requested changes

2019-03-15 23:39 UTC, johngrib commented on ios/FarmTimer/readme.md
> +# 구조
`##`를 써서 `FarmTimer for iOS`의 자식으로 표현하는 게 어떨까요?

2019-03-16 00:10 UTC, rollmind commented on ios/FarmTimer/readme.md
> +# 구조
@johngrib 반영했습니다~

2019-03-16 04:06 UTC, johngrib approved these changes

2019-03-16 08:05 UTC, merged